### ISSUE TITLE
custom sieve registry not working

### ISSUE THREAD

**Issue by VaiN474** [Jozufozu/ExNihiloOmnia#20]
I was hoping to make a custom registry but it doesn't seem to work with the example given. I copied the example over to a new file `test.json` and it doesn't allow sieving leaves and gravel just gives the gravel block back.

On another note, it's difficult to simply add something to the existing registry when there isn't one. For example if you just want to add another entry to gravel, you would have to recreate the existing registry entry for everything else as well. I do like the idea of being able to add separate files to keep things organized, but would it be possible to include a complete json file with the default settings that can be modified?

**Comment by BlayTheNinth** [comment]
Note that moving defaults to a json file is always problematic as changes in later versions of the mod won't be applied to users who ran it before, unless you do some spooky versioning magic.

The best way to solve this issue is probably allowing 1) disabling of individual default entries and then 2) making new entries append to existing entries rather than overriding them.

**Comment by VaiN474** [comment]
i'd expect it to be more like a config file, in that if you need changes from an update then the user would backup/remove the file for it to be recreated at launch. or use a hash check to determine if there were no changes and then just replace the file at launch maybe?

more important right now, is that the registry doesn't seem to function as is. if the example given doesn't work, i'm not really sure how to add my own entries.

**Comment by Drakma** [comment]
Can confirm.  Adding blocks to the sieve registry merely gives back two of the blocks you put in.
