### ISSUE TITLE
Composting Leaves in Oak Barrel gives negative stack size

### ISSUE THREAD

**Issue by jdratlif** [Jozufozu/ExNihiloOmnia#63]
I have a set of 8 barrels, and a stack of leaves. Based on Waila, and past experience with Ex Nihilo (but not Omnia) I think it should take 8 leaves per piece of dirt. When I hold down right click to continue adding leaves, I can run out of leaves, and see the stack size go negative. If I throw away this negative size stack, nothing drops. If I use inventory tweaks and sort, it depends on whether I have more leaves. If I do, they combine into the correct amount, if not, I keep my negative leave stack.

I tested this in a single player world on MC 1.10.2 with Forge 2066 (recommended version for 1.10.2 as of Oct 17 2016) with Ex Nihilo Omnia 1.1.4 as the only installed mod. I edited the default Omnia config in three places. 1) I disabled moss spread in world generation based on an earlier issue with 1.1.4. 2) I enabled void generation of all dimensions using the sky block 2.1 map.

My world is available for download at http://games.technoplaza.net/temp/TestCompost.zip showing the negative stack size.

**Comment by jdratlif** [comment]
Also, are leaves supposed to compost into podzol rather than dirt. I thought maybe this was a change from ex nihilo, but it's not mentioned on the project page.

Maybe related to this issue. If I fill the barrel before I "run out" of leaves, I get podzol. If I run out, then it becomes dirt.

Also, I noticed the same issue with oak saplings, so it's not just leaves. Seems to be related to the barrel, rather than the material.

**Comment by kreezxil** [comment]
I am having the same issues with saplings in version 1.1.4 of the mod on my multiplayer server. Right clicking any sized stack of saplings onto any barrel causes the barrel to fill up with composting material, the stack goes negative, I can continue to use this negative stack to fill the other barrels. Do anything else with the stack causes it to vanish as it should.

**Comment by jwmwebdev** [comment]
Here is my experience with this issue. I usually use oak leaf blocks, but I imagine it also happens with other leaves. Start with an empty barrel and a single leaf block. I don't think it happens in creative, but definitely happens in survival. The first usage of the leaf block will register as a single usage in the barrel, but two usage's on the leaf block. You will then have a negative-size stack of leaf blocks to dupe with.

If you use any negative-sized stack of leaves to fill a barrel, you will get normal dirt, while a positive-sized stack gives podzol.
You can use the leaf blocks as spacers in a build, as they are easy to break, and are technically duped.

Some observations on negative-sized stacks, for those curious:
The color of the text changes to red, instead of the usual white.
The stack disappears if you try to move it in your inventory.
The stack disappears if you try to mine with it.
Sometimes the stack overflows into a large positive value stack (over 100. Unsure of exact timing/size)

Currently using version 1.1.4, forge 2107

Edit: minor formating

**Comment by wentehcoolest** [comment]
Author said its fixed I on my post w/c was closed- It's because empty barrels ALWAYS seem to get 2pcs of items you put in, thus holding a single piece of compost material will give it a negative value.
1-2=-1
Math~ :)

**Comment by scottosx** [comment]
I am having this issue too. Not fixed in the current version from Curse.

It is strange. After it goes to negative numbers I get dirt instead of podzol. Even more weird, I sometimes get grass blocks.

**Comment by scottosx** [comment]
It seems to happen when you start with a full stack of 64 leaves. Also, going slow when you add them. It sometimes takes two items when you only click once. Then the count is off. When you are left with 1 leaf item in your hotbar and you click to add that then then it will let you continue into negative numbers.
You then have infinite leaves until you break the barrel.

**Comment by Jozufozu** [comment]
Fixed in commit 4593da85922a6f519b7a2779827a0b597eb3d3f9
